run:
	python main.py localhost 80

test:
	python main.py localhost 8080

hsocket:
	python -c 'import socket; help(socket)'

hlib:
	python -c 'import httplib; help(httplib)'

hhttp:
	python -c 'import BaseHTTPServer; help(BaseHTTPServer)'

hcgi:
	python -c 'import CGIHTTPServer; help(CGIHTTPServer)'

hss:
	python -c 'import SocketServer; help(SocketServer)'

hfile:
	python -c 'help(file)'

hjinja2:
	python -c 'import jinja2; help(jinja2)'

hurlparse:
	python -c 'import urlparse; help(urlparse)'
